modLoader="javafml"
loaderVersion="[32,)"
[[mods]]
modId="bk"
version="${file.jarVersion}"
displayName="Beekeeper"
displayURL="https://www.curseforge.com/minecraft/mc-mods/beekeeper"
logoFile="logo.png"
authors="Lupicus, MacTso"
description='''Beekeeper'''
[[dependencies.bk]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bk]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
